# Generated by Django 3.2 on 2022-03-13 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0002_alter_followcoins_coins_string'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotecoin',
            name='latest',
            field=models.BooleanField(default=False, verbose_name='Latest'),
            preserve_default=False,
        ),
    ]
