# Generated by Django 3.2 on 2022-03-13 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0003_quotecoin_latest'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotecoin',
            name='coin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='coins.coin'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coin',
            name='announcement',
            field=models.CharField(max_length=400, verbose_name='Announcement'),
        ),
        migrations.AlterField(
            model_name='coin',
            name='chat',
            field=models.CharField(max_length=400, verbose_name='Chat'),
        ),
        migrations.AlterField(
            model_name='coin',
            name='message_board',
            field=models.CharField(max_length=400, verbose_name='Message Board'),
        ),
        migrations.AlterField(
            model_name='coin',
            name='reddit',
            field=models.CharField(max_length=400, verbose_name='Reddit'),
        ),
        migrations.AlterField(
            model_name='coin',
            name='source_code',
            field=models.CharField(max_length=400, verbose_name='Source Code'),
        ),
        migrations.AlterField(
            model_name='coin',
            name='technical_doc',
            field=models.CharField(max_length=400, verbose_name='Technical Doc'),
        ),
        migrations.AlterField(
            model_name='coin',
            name='twitter',
            field=models.CharField(max_length=400, verbose_name='Twitter'),
        ),
    ]
